# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-14 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_shayari_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shayari_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
