# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-20 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190414_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=120)),
                ('Telephone', models.CharField(max_length=120)),
                ('Subject', models.CharField(max_length=120)),
                ('Message', models.TextField()),
            ],
        ),
    ]
